apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    env: dev
    app: mongodb
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
      app: mongodb
      tier: db
  template:
    metadata:
      labels:
        env: dev
        app: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: mohan1424/catalogue:1.0.0
---
apiVersion: v1 
kind: Service
metadata: 
  name: mongodb
  namespace: roboshop
spec:
  selector:
    env: dev
    app: mongodb 
    tier: db
  ports: 
    - name: mongodb-port
      protocol: TCP
      port: 27017
      targetPort: 27017
     


    