# First Deployment (apps/v1)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-dev
  labels:
    env: dev
    app: mongodb
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
      app: mongodb
      tier: db
  template:
    metadata:
      labels:
        env: dev
        app: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: mohan1424/mongodb:1.0.0

---

# Second Deployment (v1)
apiVersion: v1 
kind: Deployment
metadata: 
  name: mongodb-prod
spec:
  selector:
    matchLabels:
      env: prod
      app: mongodb 
      tier: db
  ports: 
    - name: mongodb-port
      protocol: TCP
      port: 27017
      targetPort: 27017
