apiVersion: apps/v1
kind: Deployment
metadata:
  name: fronn1
  labels: 
    env: dev
    app: frontend
spec: 
  replicas: 3
  selector: 
    matchLabels:
      env: dev1
      app: frontend1
  template:
    metadata:
      labels:
        env: dev1
        app: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
      
      
