apiVersion: v1
kind: Pod
metadata: 
  name: pod-config
spec:
  containers:
  - name: demo
    image: nginx
    env:
    - name: course
      valuefrom:
        ConfigMapKeyRef:
          name: config
          key: course
    - name: student
      valuefrom: 
        ConfigMapKeyRef:
          name: config
          key: student