apiVersion: v1
kind: Pod
metadata: 
  name: pod-config
spec:
  containers:
  - name: pod-config
    image: nginx
    env:
    - name: course
      valueFrom:
        configMapKeyRef:
          name: confi
          key: course
    - name: student
      valueFrom:
        configMapKeyRef:
          name: confi
          key: student
