apiVersion: v1
kind: Pod
metadata:
  name: nginx
  lables:
    enviroment: dev
    app: frontend
spec:
  containers: 
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
        name: http-web
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    enviroment: dev
    app: frontend
  ports:
  - name: port-service
    protocol: tcp
    port: 80
    targetPort: http-web
