apiVersion: v1
kind: Secret
metadata:
  name: s
data:
  username: bW9oYW4K
  password: bW9oYW4xNDI0Mgo=
---
apiVersion: v1
kind: Pod
metadata: 
  name: secretepod
spec:
  containers:
  - name: pod-config
    image: nginx
    envFrom:
    - secretRef: 
        name: s