apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    env: dev
    app: catalogue
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
      app: catalogue
      tier: db
  template:
    metadata:
      labels:
        env: dev
        app: catalogue
        tier: db
    spec:
      containers:
      - name: mongodb
        image: mohan1424/catalogue:1.0.0
        envFrom:
        - configMapRef:
            name: catalogue
      
---
apiVersion: v1 
kind: Service
metadata: 
  name: catalogue
  namespace: roboshop
spec:
  selector:
    env: dev
    app: catalogue
    tier: db
  ports: 
    - name: mongodb-port
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1 
Kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop 
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
     


    